apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins.zenvo.ai
  namespace: jenkins
spec:
  secretName: jenkins-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - https://jenkins.zenvo.ai
