apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-docker-registry
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/k8s-volume/registry"
