apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-docker-registry
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: docker-storage
  nfs:
    path: /mnt/k8s-volume/docker-registry
    server: 192.168.0.104
