apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-docker-registry
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.coherent.in
    path: "/mnt/k8s-volume/nfs/k8s/localk8s/docker-registry"
  mountOptions:
    - nfsvers=4.2
