apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-docker-registry
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-docker-registry
