apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-docker-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: docker-storage
